@xset s off
@xset -dpms
@xset s noblank
@unclutter -idle 0.5 -root
@chromium-browser --noerrdialogs --disable-infobars --kiosk --incognito --check-for-update-interval=31536000 http://<GATEWAY_HOST>:18789/__openclaw__/canvas/
